// Compound Assignment Operators: Use compound assignment operators to simplify arithmetic operations. Start with x = 4 and perform a series of operations (addition, subtraction, multiplication, division) on x using compound operators.
var x = 4;
x += 3; // Initially, x is 4. After addition, x becomes 7.
console.log("After Addition: x =", x);
x -= 3; // Starting with x as 7, after subtraction, x becomes 4.
console.log("After Subtraction: x =", x);
x *= 3; // Beginning with x as 4, after multiplication, x becomes 12.
console.log("After Multiplication: x =", x);
x /= 3; // With x initially as 12, after division, x becomes 4.
console.log("After Division: x =", x);
