// Compound Assignment Operators: Use compound assignment operators to simplify arithmetic operations. Start with x = 4 and perform a series of operations (addition, subtraction, multiplication, division) on x using compound operators.
var x = 4;
x += 3; // Here initial x is 4
console.log("After Addition: x =", x);
x -= 3; // Here initial x will 7
console.log("After Subtraction: x =", x);
x *= 3; // Here initial x will 4
console.log("After Multiplication: x =", x);
x /= 3; // Here initial x will 12
console.log("After Division: x =", x);
